ChocOvation/Models/Offer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChocOvation.Models
{
    public class Offer
    {
        [Display(Name = "Offer ID")]
        public int OfferID { get; set; }

        [ForeignKey("SupplierID")]
        public Supplier Supplier { get; set; }
        public string SupplierID { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Offer's Date")]
        [Column(TypeName = "Date")]
        public DateTime DateOfOffer { get; set; }

        public IEnumerable<OfferPerMaterial> OffersPerMaterial { get; set; }

        public float? TotalPriceQuality { get; set; }
    }
}

ChocOvation/Controllers/OfferController.cs
using ChocOvation.Models;
using ChocOvation.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ChocOvation.Controllers
{
    [Authorize(Roles = "Supplier, CEO, Admin")]
    public class OfferController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult MyOffers()
        {

            var userId = User.Identity.GetUserId();


            var myOffers = db.Offers
                .Where(a => a.SupplierID == userId)
                .ToList();


            return View(myOffers);
        }

        // GET: Offer
        [Authorize]
        public async Task<ActionResult> BestOffers()
        {
            var offers = db.Offers.Include(o => o.Supplier).OrderByDescending(o => o.TotalPriceQuality).Take(3);

            ViewBag.checkRole = User.IsInRole("Admin");

            return View(await offers.ToListAsync());
        }

        // GET: Offer
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var offers = db.Offers.Include(o => o.Supplier).OrderByDescending(o => o.TotalPriceQuality);

            ViewBag.checkRole = User.IsInRole("Admin");

            return View(await offers.ToListAsync());
        }

        // GET: Offer/Details/5
        public async Task<ActionResult> Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = await db.Offers.FindAsync(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            var offersPerMaterial = db.OffersPerMaterials
                .Where(s => s.OfferID == id)
                .Include(s => s.Material)
                .ToList();


            var ListOfLittleOffers = offersPerMaterial.AsEnumerable();


            ViewBag.checkRole = User.IsInRole("Supplier");
            ViewBag.supID = offer.SupplierID;
            return View(ListOfLittleOffers);
        }

        // GET: Offer/Create
        [Authorize]
        public ActionResult Create()
        {
            var distinctmaterials = db.Materials.Select(m => m.MaterialName).Distinct().ToList();
            var numberOfMaterials = distinctmaterials.Count();
            OfferFormViewModel[] LittleOffers = new OfferFormViewModel[numberOfMaterials];

            for (int i = 0; i < numberOfMaterials; i++)
            {
                var viewModel = new OfferFormViewModel();
                viewModel.MaterialName = distinctmaterials[i];
                viewModel.Quality = Quality.High;
                viewModel.PricePerKg = 1;

                LittleOffers[i] = viewModel;
            }

            var ListOfLittleOffers = LittleOffers.ToList();

            return View(ListOfLittleOffers);
        }


        // POST: Offer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MaterialName,Quality,PricePerKg")] List<OfferFormViewModel> viewModel)
        {
            var distinctmaterials = db.Materials.Select(m => m.MaterialName).Distinct().ToList();
            var numberOfMaterials = distinctmaterials.Count();

            if (ModelState.IsValid)
            {
                var offer = new Offer();
                offer.DateOfOffer = DateTime.Today;
                offer.SupplierID = User.Identity.GetUserId();
                db.Offers.Add(offer);
                await db.SaveChangesAsync();
                float? index = 0;

                foreach (var item in viewModel)
                {
                    var materialID = db.Materials
                        .Where(m => (m.MaterialName == item.MaterialName)
                        && (m.Quality == item.Quality))
                        .Select(i => i.MaterialID)
                        .FirstOrDefault();


                    var littleOffer = new OfferPerMaterial
                    {
                        OfferID = offer.OfferID,
                        MaterialID = materialID,
                        PricePerKg = item.PricePerKg,
                        PriceQuality = item.PriceANDQuality
                    };
                    index = index + littleOffer.PriceQuality;
                    db.OffersPerMaterials.Add(littleOffer);
                    await db.SaveChangesAsync();
                }


                if (db.OffersPerMaterials.Count() != 0)
                {

                    offer.TotalPriceQuality = (100 * index) / db.OffersPerMaterials.Count();
                }
                await db.SaveChangesAsync();

                return RedirectToAction("MyOffers");
            }
            return View(viewModel);
        }

        // GET: Offer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var offer = db.Offers.Where(o => o.OfferID == id).Include(o => o.Supplier).Single();
            if (offer == null)
            {
                return HttpNotFound();
            }
            ViewBag.checkRole = User.IsInRole("Supplier");

            return View(offer);
        }

        // POST: Offer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "OfferID,SupplierID,DateOfOffer")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("MyOffers");
            }

            ViewBag.checkRole = User.IsInRole("Supplier");
            //ViewBag.supID = offer.SupplierID;
            return View(offer);
        }

        // GET: Offer/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            ViewBag.checkRole = User.IsInRole("Supplier");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = await db.Offers.FindAsync(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);

        }

        // POST: Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            bool check = User.IsInRole("Supplier");

            Offer offer = await db.Offers.FindAsync(id);
            db.Offers.Remove(offer);
            await db.SaveChangesAsync();

            if (check)
            {
                return RedirectToAction("MyOffers");
            }
            else
            {
                return RedirectToAction("Index");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChocOvation/Views/Offer/BestOffers.cshtml
@model IEnumerable<ChocOvation.Models.Offer>

@{
    ViewBag.Title = "BestOffers";
}

<h2>The Top 3 Offers!!!</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Supplier.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfOffer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPriceQuality)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfOffer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPriceQuality)
            </td>




            @{  var check = ViewBag.checkRole;


                if (check)
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.OfferID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.OfferID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.OfferID })
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.OfferID }) |
                        @Html.ActionLink("Select", "Create", "Order", new { id = item.OfferID }, htmlAttributes: new { @class = "" })
                    </td>
                }



            }
        </tr>
                }

</table>

ChocOvation/Views/Offer/Create.cshtml
@model List<ChocOvation.ViewModels.OfferFormViewModel>

@{
    ViewBag.Title = "Create";
}

<h2 style="height:50px; padding-left:200px">Create Your Offer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container ">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="container">
            <div class="row  items">
                <div class="item col-md-4">
                    <h4>Material Name</h4>
                </div>
                <div class="item col-md-4">
                    <h4>Quality</h4>
                </div>
                <div class="item col-md-4">
                    <h4>Price</h4>
                </div>
               
                @{  for (int x = 0; x < Model.Count(); x++)
                    {
                        <div class="item col-md-4" , name="MaterialName">                                                 
                            @Html.TextBoxFor(m => Model[x].MaterialName, new {@readonly="readonly", @class = "form-control", autofocus = "autofocus" })
                        </div>
                        <div class="item col-md-4" , name="Quality">
                            @Html.EnumDropDownListFor(m => Model[x].Quality, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => Model[x].Quality, String.Empty, new { @class = "text-danger" })
                        </div>

                        <div class="item col-md-4">
                            <div class="input type=" text" name="PricePerKg" col-sm-3 col-md-6">
                                @Html.TextBoxFor(m => Model[x].PricePerKg, new { @class = "form-control", autofocus = "autofocus" })
                                @Html.ValidationMessageFor(m => Model[x].PricePerKg, String.Empty, new { @class = "text-danger" })
                            </div>
                        </div>                        
                    }

                }
            </div>
        </div>
    </div>


    <div class="container">
        <div class="col-md-offset-2 col-md-6">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>

        <div class="col-md-offset-2 col-md-6">
            @Html.ActionLink("Back to List", "MyOffers")
        </div>
    </div>
 }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChocOvation/Views/Offer/Delete.cshtml
@model ChocOvation.Models.Offer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Offer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Total Price/Quality
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPriceQuality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfOffer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfOffer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @{  var check = ViewBag.checkRole;

                if (check)
                {
                    @Html.ActionLink("Back to List", "MyOffers")
                }
                else
                {
                    @Html.ActionLink("Back to list", "Index", "Offer"@*, new { id = supplierid }, htmlAttributes: new { @class = "" }*@)
                }

            }
            
        </div>
    }
</div>

ChocOvation/Views/Offer/Details.cshtml
@model IEnumerable<ChocOvation.Models.OfferPerMaterial>

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>


    <h4>Offer</h4>
    <hr />

    
        @*<dt>
            @Html.DisplayNameFor(model => model.SupplierID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SupplierID)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.DateOfOffer)
        </dt>

        <dd>
            @Html.DisplayFor(modelItem => model.)
        </dd>*@
<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <h5><b>Material Name</b></h5>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Material.MaterialName)
            </td>
        </tr>
            <tr>
                <td>
                    <h5><b>Quality</b></h5>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Material.Quality)
                </td>

            </tr>
            <tr>
                <td>
                    <h5><b>Price Per Kilo</b></h5>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PricePerKg)
                </td>

            </tr>
            <tr style="border-bottom:double" >
                <td>
                   <h5> <b>Price/Quality</b></h5>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PriceQuality)
                </td>

            </tr>
            


                }

</table>

<p>
    @{  var check = ViewBag.checkRole;
        var supplierid = ViewBag.supID;


        if (check)
        {
            @Html.ActionLink("Back to List", "MyOffers")                                                         
        }
        else
        {
            @Html.ActionLink("Back to list", "Index", "Offer"@*, new { id = supplierid }, htmlAttributes: new { @class = "" }*@)
        }

    }
    
</p>

ChocOvation/Views/Offer/Edit.cshtml
@model ChocOvation.Models.Offer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Offer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OfferID)

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplier.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supplier.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfOffer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfOffer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfOffer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@{  var check = ViewBag.checkRole;
    
    if (check)
    {
        @Html.ActionLink("Back to List", "MyOffers")
    }
    else
    {
        @Html.ActionLink("Back to list", "Index", "Offer"@*, new { id = supplierid }, htmlAttributes: new { @class = "" }*@)
    }

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChocOvation/Views/Offer/Index.cshtml
@model IEnumerable<ChocOvation.Models.Offer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Supplier.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfOffer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPriceQuality)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfOffer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPriceQuality)
        </td>


        

            @{  var check = ViewBag.checkRole;


                if (check)
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.OfferID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.OfferID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.OfferID })
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.OfferID }) 
                        @*@Html.ActionLink("Select", "Create", "Order", new { id = item.OfferID }, htmlAttributes: new { @class = "" })*@
                    </td>
                }



            }
    </tr>
}

</table>

ChocOvation/Views/Offer/MyOffers.cshtml
@model IEnumerable<ChocOvation.Models.Offer>

@{
    ViewBag.Title = "MyOffers";
}

<h2>My Offers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>        
        <th>
            @Html.DisplayNameFor(model => model.DateOfOffer)
        </th>
        <th>
            Index Of Quality/Price          
        </th>
        @*<th>
            Offer Per Material
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>        
        <td>
            @Html.DisplayFor(modelItem => item.DateOfOffer)
        </td>
        <td>            
            @Html.DisplayFor(modelItem => item.TotalPriceQuality)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.DateOfOffer)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OfferID }) |
            @Html.ActionLink("Details", "Details", new { id=item.OfferID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OfferID })
        </td>
    </tr>
}

</table>